README.md

This is not a comprehensive review.

fix: correct some spelling mistakes

---

src/lang/locale/en.ts

Thanks for this incredible plugin! :)

Fix three typos in English localization

---

ea-scripts/Fixed spacing.md
ea-scripts/Fixed vertical distance.md
ea-scripts/Modify background color opacity.md

Fault tolerance is implemented for cases where the user presses the ESC key in the input box and the input value will be NaN.

Fixed 3 scripts that did not handle NaN input values

---

src/lang/locale/zh-cn.ts

The *zh-cn.ts* seemed a bit out of date since this plugin has developed a lot. So I went through the file and made some adjustment, correction and complement to keep it updated with the newest 1.5.17 en.ts.

Update zh-cn.ts to 1.5.17

---

ea-scripts/Expand rectangles vertically.md

Update Expand rectangles vertically.md

---

src/ExcalidrawView.ts

Fixes a small typo I noticed today

Fixes a typo in the fullscreen action

---

README.md

Fix spelling errors in readme

---

ea-scripts/Add Next Step in Process.md

next-step: Supports fit ellipse diamond shape

---

README.md

fixed typos & syntax errors

---

docs/API/introduction.md

Fixed for grammatical correctness and does not affect the ideas communicated in the file.

Grammar fix

---

src/lang/locale/en.ts

Just like the title says. Less typos mean more happy users :)

Fixed some typos

---

src/lang/locale/zh-cn.ts

I update zh-cn language to 2.2.3,  But I encountered an error when trying to build (unrelated to the language file, I just don't know how to proceed), please test it before releasing, thank you.

Update zh-cn language to 2.2.3

---

docs/Examples/templater_mindmap.md

Small grammar update and getting knowledge on how to submit a PR to an upstream forked repo.

Update templater_mindmap.md grammar

---

src/lang/locale/zh-cn.ts

- Updated to 2.2.6
- Some punctuation to Chinese punctuation
- Add space between Chinese and English
- Change keyname to just first letter upper
- Remove space at line end

Updated and formated zh-cn.ts

---

README.md
docs/zh-cn/AutomateHowTo.md
docs/zh-cn/README.md
src/lang/locale/zh-cn.ts

Add a folder in ./docs for more Chinese docs, and move zh-cn README into it. Translated AutomateHowTo.md

Update zh-cn.ts to 2.4.3

---

docs/zh-cn/AutomateHowTo.md
docs/zh-cn/README.md
src/lang/locale/zh-cn.ts

Update zh-cn.ts to 74c0af2

---

README.md

Addressing #2037 
- Change `customColorPalette` to `colorPalette`
- Add section about `topPicks`
- Add hint to "Decompress Excalidraw JSON in Markdown View" to *templates* section
- Add hint to "Decompress Excalidraw JSON in Markdown View" to *markdown* section

Update color palette details in README

---

MathjaxToSVG/index.ts
src/ExcalidrawView.ts
src/utils/CropImage.ts
src/utils/FileUtils.ts
src/utils/Utils.ts

exitFullscreen when closing the view.

fixed unescape, decodeURIComponent issue with non-latin characters.

---

src/lang/locale/zh-cn.ts

Please don't use auto formater in language file, now, in zh-cn.ts, every items have the same line-number with en.ts, for easy to find and change.

Update zh-cn.ts to 6733f76

---

src/lang/locale/zh-cn.ts

And remove spaces from line end

Update zh-cn.ts to 22d3f25

---

MathjaxToSVG/index.ts
src/shared/ExcalidrawAutomate.ts
src/shared/ExcalidrawData.ts

Should fix #2195 in a bit of a hacky way and fix #1842 trimming useless spacing characters around the string

Fixing a couple issues with LaTeX

---

README.md
docs/readme.md
docs/zh-cn/README.md
docs/zh-cn/docs/ExcalidrawScriptsEngine.md
docs/zh-cn/docs/Release-notes.md
docs/zh-cn/docs/readme.md
docs/zh-cn/ea-scripts/README.md
ea-scripts/README.md

Added Chinese translation for the script index page (es-scripts/readme_CN.md)
Updated the format of language switcher links in both Chinese and English documentation

es-scripts/readme.md at 768aebf

---

src/lang/locale/es.ts

Synchronized the `es.ts` translation file with the latest `en.ts` to ensure consistency and introduce improved phrasing.
Key changes include:
- Corrected some variable names to align with the source file `en.ts`.

Update es.ts to 01b0b64a

---

src/lang/locale/zh-cn.ts

This translation update involves many old translations and will take some time to unify.

Update zh-cn.ts to 5bf7271

---

src/lang/locale/zh-cn.ts

Including the unfinished part of #2454, updated zh-cn.ts to the latest and unified all the related old translations.

Update zh-cn.ts to 425d830

---

src/lang/locale/zh-cn.ts

Update zh-cn.ts to 37543c6
