ea-scripts/Modify background color opacity.md
This script changes the **opacity** of the background color of the selected boxes.
The default background color in Excalidraw is so dark that the text is hard to read. You can lighten the color a bit by setting transparency. And you can tweak the transparency over and over again until you're happy with it.
Although excalidraw has the opacity option in its native property Settings, it also changes the transparency of the border. Use this script to change only the opacity of the background color without affecting the border.
=> Add Modify background color opacity ea-scripts file

ea-scripts/Fixed spacing.md, ea-scripts/Fixed vertical distance.md
`Fixed spacing` arranges the selected elements horizontally with a fixed spacing.
`Fixed vertical distance` arranges the selected elements vertically with a fixed spacing.
When we create an architecture diagram or mind map, we often need to arrange a large number of elements in a fixed spacing. `Fixed spacing` and `Fixed vertical Distance` scripts can save us a lot of time.
ps. My English is not good, if you have a more appropriate script name, please help me correct it.
=> Add Fixed spacing etc. ea-scripts files

ea-scripts/Expand rectangles horizontally.md, ea-scripts/Expand rectangles vertically.md
`Expand rectangles horizontally` and `Expand rectangles vertically` should not change the position of text elements.
=> Fix unnecessary changes to text placement

src/main.ts
When used with the Hover Editor plugin and the menus of Quick Explorer or Pane Relief, the old way of pushing a scope caused Excalidraw to take control away from the menu scope.  This change adds a handler to the app's root scope at a precedence above hotkey commands, but below that of any currently-pushed scopes (such as menus or modals).
(See https://github.com/nothingislost/obsidian-hover-editor/issues/85 for more background.)
=> Don't override menu scope in hover editor

src/lang/locale/en.ts
the text appears as this:
(or just Excalidraw/Template - you may ommit the .md file extensionIf
and this pr (should) change it to this:
(or just Excalidraw/Template - you may ommit the .md file extension). If
=> fix typo in english plugin settings

ea-scripts/README.md
The script installation instructions were out of date and the scripts did not show up until I fully restarted Obsidian, just opening a new Excalidraw drawing was not enough (perhaps because I had excalibrain open in a pop-out window?)
=> Update script installation instructions

ea-scripts/Convert selected text elements to sticky notes.md
In this video: https://youtu.be/fXGcOWycgG4?t=1923
it is mentioned that the default border color for the "Convert selected text elements to sticky notes" script is a transparent border, however that is not the current default value.
I think setting `transparent` as the default is more useful than `#000000` because `transparent` can only be set via a script (at least without affecting the text color) while `#000000` can be set since it is also a common color for text.
=> Change the default sticky note to have transparent border

src/lang/locale/en.ts
Just a few typos/inconsistencies I noticed during my usage. Did not read through every single setting, but these are some I noticed over a little bit of time.
=> English settings page - Language/typo fixes

ea-scripts/Mindmap format.md
=> Fixed issue with mindmap format script that elements within group were not formatted along with selected element

ea-scripts/Add Next Step in Process.md
=> feat: next step style same as previous rect

src/lang/locale/en.ts
Fixes grammatical errors in the English translation file (`src/lang/locale/en.ts`) where some instances of the word "effect" should have been "affect".
=> Fix grammatical "effect" "affect" issues

src/ExcalidrawView.ts
Pretty primtiive check, but it seems to work from my testing, either way it will only have an effect on linux since it checks for DEVICE.isLinux().
https://github.com/zsviczian/obsidian-excalidraw-plugin/assets/96164686/7998c865-9db9-4e3f-9894-c61f2b4d0b26
>(It doesn't happen everytime you try pan, but it happens often enough that I booted into windows at points just to use excalidraw)
I also left in a comment that references auxclick, I couldn't get that one to work, however it should be possible to do with auxclick according to [this from the MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event#preventing_default_actions)
Fixes: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1215 *---  [:)](https://youtu.be/L_WoOkDAqbM)*
=> Fix Excalidraw Pasting with middle mouse button on linux

src/lang/locale/en.ts, src/main.ts, src/utils/ObsidianUtils.ts
Addresses #1348. 
Adds the ability to specifying saving new drawings into the current folder or a folder within the current folder. I see the above issue when I wanted to see if it was possible to save drawings into the current folder. I wanted to the ability to have my excalidraws in the current folder (or subfolder) of my active note while being able to separate it from my attachments which I have in a folder at the vault root.
I used the `getAttachmentsFolderAndFilePath()` in ObsidianUtils.ts as reference for handling the various folder options that `app.vault.getConfig("attachmentFolderPath")` returns. 
Since the current logic currently allows saving new drawings to a folder in the vault root or directly to the vault root, the "./" and the "./folder" options is what is being added in …
=> FR: Update Excalidraw Folder setting to allow saving drawings in the current folder or subfolder within current folder #1348

src/ExcalidrawView.ts, src/main.ts, src/settings.ts
I've removed the `autosaveInterval` variable from the settings interface, and within the timer function setup a local variable set to the appropriate mobile or desktop version of the variable.
=> Remove autosaveInterval variable but preserve functionality

README.md
**Issue:**
- The README contains a broken link to a not-on-main file documenting how to add custom pens. (That document was archived.) 
- The README hard-links to the master branch of the EA folder rather than to whatever branch the GH user is on. I have made that link relative, so that when looking at a different branch, the links are relative to the branch the user is searching around on.
**Fix:**
- Pens are now handled in settings with a different YouTube video showing how to set them up (I think). 
- Adds links to the Hardware Eraser functionality & Auto Draw for Pen. 
Open Question/Discussion:
- I think it might be useful to link to the freestyle docs here still, or have some sort of master "Alternative Pens" link that still shows how to do the JSON setup as opposed to the UI setup? …
=> Documentation: Update Custom Pens documentation links

ea-scripts/ExcaliAI.md
Right now I am getting this error when trying to use ExcaliAI when an image is selected.
This PR updates request json from `{image: imageDataURL}` to `{image: {url: imageDataURL}}`
=> Update ExcaliAI.md to fix incorrect request json for openai api

manifest.json
I noticed that the `authorUrl` in the manifest does not work, as it's missing the `www`.
=> Fix `authorUrl` in manifest

src/ExcalidrawData.ts
The Excalidraw [JSON schema](https://docs.excalidraw.com/docs/codebase/json-schema) clearly requires the `source` property, but some Excalidraw implementations do not include this.
In the case of Nextcloud Whiteboard, which does not include the `source` property in its Excalidraw JSON, causes this plugin to hang when trying to render the drawing in legacy mode.
This PR uses the optional chaining (?.) feature of JS to gracefully accept a missing `source` property.
=> Allow poorly formated .excalidraw files to render 

MathjaxToSVG/index.ts, src/core/settings.ts, src/lang/locale/en.ts, src/shared/EmbeddedFileLoader.ts, src/shared/ExcalidrawAutomate.ts, src/shared/LaTeX.ts
Added the option to specify a custom location for the preamble file, leaving the default for backward compatibility.
Fixes #1631 separating the preamble and the inserted latex with a `\n`.
=> Allow custom location for LaTeX preamble file and small fix

src/utils/obsidianUtils.ts, src/utils/utils.ts
While current implementation is technically correct
1. It almost fully repeats internal `app.vault.getAvailablePathForAttachments()` implementation.
2. It is not fully compatible with [Custom Attachment location](https://github.com/RainCat1998/obsidian-custom-attachment-location) plugin features.
The bug https://github.com/RainCat1998/obsidian-custom-attachment-location/issues/179 cannot be fixed without making this PR in `Excalidraw` plugin.
=> Use internal `app.vault.getAvailablePathForAttachments()`

src/lang/locale/zh-cn.ts
as it is inherited from upstream (e.g. in the toolbar's frame tool) and cannot be changed by the plugin.
During the revision, I also noticed that some other Chinese translations could be clearer and more consistent. I will kindly show the details below.
=> Unify zh-cn.ts translation of 'frame' to '画框' to follow the upstream default
